### ISSUE TITLE
Detailed explanation required

### ISSUE THREAD

**Issue by ajaygm1818** [sahilkargutkar/Sflix#1]
It gave error when I ran npm start
Failed to compile.                                                                                                                                              src/lib/firebase.prod.js                                                          Line 10:13:  'apiKey' is not defined             no-undef                       Line 11:17:  'authDomain' is not defined         no-undef                       Line 12:16:  'projectId' is not defined          no-undef                       Line 13:20:  'storageBucket' is not defined      no-undef                       Line 14:24:  'messagingSenderId' is not defined  no-undef                       Line 15:12:  'appId' is not defined              no-undef                                                                                                     Search for the keywords to learn more about each error.

**Comment by sahilkargutkar** [comment]
hey, thanks for messaging me about the issues you are facing."apiKey" and other errors are your personal ids which you get after setting up firebase.you just have to copy and paste the key after setting up firebase.you can use this https://youtu.be/PKwu15ldZ7k to solve your issues
